/*
CREATING BASIC SCHEMA TABLE
*/
CREATE TABLE USERS(
first_name VARCHAR2(50),
last_name VARCHAR2(50),
password VARCHAR2(50),
email VARCHAR2(50),
mobile_no CHAR(10),
wallet_money NUMBER(10,2),
role_name VARCHAR2(50)
);


CREATE TABLE VEHICLE(
vehicle_model VARCHAR2(50),
vehicle_owner VARCHAR2(50),
vehicle_number CHAR(10),
vehicle_type_name VARCHAR2(100),
vehicle_category_name VARCHAR2(50),
color VARCHAR2(50),
location VARCHAR2(50),
location_name VARCHAR2(50),
addresss VARCHAR2(100),
city VARCHAR2(50),
pincode CHAR(6),
vehicle_image_url VARCHAR2(500),
cost_per_hour NUMBER(10,2),
fuel_type VARCHAR2(50)
);

DESC VEHICLE;

CREATE TABLE BOOKING(
pickup_date DATE,
dropoff_date DATE,
booking_date DATE,
amount NUMBER(10,2),
location_name VARCHAR2(50)
);

DESC BOOKING

CREATE TABLE REQUEST(
activity_type VARCHAR2(50),
user_comments VARCHAR2(50),
admin_comments VARCHAR2(50),
request_status VARCHAR2(50),
vehicle_number VARCHAR2(50),
user_email CHAR(10)
);

DESC BOOKING ;


--ADDING CONSTRAINTS IN ABOVE TABLES

/*
ALTER TABLE table_name 
ADD column_name data_type constraint;
*/

ALTER TABLE USERS
ADD user_id CHAR(5) PRIMARY KEY ;

desc users;
/*
The basic syntax of an ALTER TABLE command to add a NOT NULL constraint to a column in a table is as follows.

ALTER TABLE table_name MODIFY column_name datatype NOT NULL;
*/
ALTER TABLE USERS
MODIFY first_name VARCHAR2(50) NOT NULL ;

ALTER TABLE USERS
MODIFY PASSWORD VARCHAR2(50) NOT NULL CHECK (Length(PASSWORD) > 5 ) ;

ALTER TABLE USERS
MODIFY EMAIL VARCHAR2(50) NOT NULL UNIQUE

ALTER TABLE USERS
MODIFY MOBILE_NO CHAR(10) NOT NULL UNIQUE

ALTER TABLE USERS
MODIFY WALLET_MONEY NUMBER(10,2) DEFAULT 10000.00

ALTER TABLE USERS
MODIFY ROLE_NAME VARCHAR2(50)  NOT NULL UNIQUE

-- DISPLAY USERS
DESC users;


-- DISPLAY VEHICLE
DESC VEHICLE

-- ADD PRIMARY KEY TO vehicle_id
ALTER TABLE VEHICLE
ADD vehicle_id CHAR(5) PRIMARY KEY

-- ADD NOT NULL CONSTRAINT TO MODEL
ALTER TABLE VEHICLE
MODIFY VEHICLE_MODEL VARCHAR2(50) NOT NULL

-- ADD FOREIGN KEY
/*
ALTER TABLE Orders
ADD FOREIGN KEY (PersonID) REFERENCES Persons(PersonID);
*/

alter table vehicle
drop column user_id

ALTER TABLE VEHICLE
ADD USER_ID CHAR(5)

ALTER TABLE VEHICLE
ADD FOREIGN KEY (user_id) REFERENCES USERS(user_id) ;

DESC VEHICLE

-- set vehicle_number as primary key
/*
ALTER TABLE Persons
ADD CONSTRAINT PK_Person PRIMARY KEY (ID,LastName);
*/

ALTER TABLE VEHICLE
DROP PRIMARY KEY;

ALTER TABLE VEHICLE
MODIFY VEHICLE_NUMBER CHAR(10) PRIMARY KEY

ALTER TABLE VEHICLE
MODIFY VEHICLE_ID CHAR(5) PRIMARY KEY

ALTER TABLE VEHICLE
ADD CONSTRAINT VEHICLE_ID_NUMBER PRIMARY KEY(VEHICLE_ID, VEHICLE_NUMBER)

ALTER TABLE VEHICLE
MODIFY VEHICLE_TYPE_NAME VARCHAR2(100) NOT NULL UNIQUE

ALTER TABLE VEHICLE
MODIFY VEHICLE_CATEGORY_NAME VARCHAR2(50) NOT NULL UNIQUE

ALTER TABLE VEHICLE
MODIFY COLOR VARCHAR2(50) NOT NULL

ALTER TABLE VEHICLE
MODIFY FUEL_TYPE VARCHAR2(50) NOT NULL UNIQUE

/*
Modify Multiple columns in table
Syntax
To MODIFY MULTIPLE COLUMNS in an existing table, the Oracle ALTER TABLE syntax is:

ALTER TABLE table_name
  MODIFY (column_1 column_type,
          column_2 column_type,
          ...
          column_n column_type);
*/
ALTER TABLE VEHICLE
MODIFY (
VEHICLE_IMAGE_URL VARCHAR2(500) NOT NULL,
LOCATION_NAME VARCHAR2(50) NOT NULL,
ADDRESSS VARCHAR2(100) NOT NULL,
CITY VARCHAR2(50) NOT NULL,
PINCODE CHAR(6) NOT NULL,
COST_PER_HOUR NUMBER(10,2) NOT NULL
)

DESC VEHICLE

-- BOOKING

desc booking

ALTER TABLE BOOKING
ADD booking_id CHAR(5) PRIMARY KEY

ALTER TABLE BOOKING
MODIFY (
PICKUP_DATE DATE NOT NULL,
DROPOFF_DATE DATE NOT NULL,
BOOKING_DATE DATE NOT NULL,
AMOUNT NUMBER(10,2) NOT NULL
)

-- adding foreign key
ALTER TABLE BOOKING
ADD vehicle_id CHAR(5) NOT NULL 

ALTER TABLE BOOKING 
ADD USER_ID CHAR(5) NOT NULL

-- ADD FOREIGN KEY
/*
ALTER TABLE Orders
ADD FOREIGN KEY (PersonID) REFERENCES Persons(PersonID);
*/
ALTER TABLE BOOKING
ADD FOREIGN KEY ( USER_ID )  REFERENCES Users( user_id) 



desc vehicle
DESC BOOKING

DESC REQUEST