select * from countries ;

select * from REGIONS ;

/* NATURAL JOIN */
-- 1
select c.COUNTRY_NAME, REGIONS.REGION_NAME
from countries c
NATURAL JOIN REGIONS ;

-- 2
SELECT * 
FROM COUNTRIES
NATURAL JOIN REGIONS ;

/* LIMITATION -: ONLY TWO TABLE'S HAVE A SAME COLUMN THEN ONLY NATURAL JOIN WILL WORK PERFECTLY, HENCE LIMITED SCOPE */

-- GENERIC JOINS
/*
1. INNER JOIN [ SIMILAR TO NATURAL JOIN ]
2. LEFT JOIN
3. RIGHT JOIN
4. FULL OUTER JOIN
*/

SELECT COUNTRIES.COUNTRY_NAME, REGIONS.REGION_NAME 
FROM COUNTRIES
INNER JOIN REGIONS 
ON REGIONS.REGION_ID = COUNTRIES.REGION_ID  
ORDER BY COUNTRIES.COUNTRY_NAME DESC
;

-- DIFFERECNCE BETWEEN INNER JOIN AND NATURAL JOIN

select c.COUNTRY_NAME, REGIONS.REGION_NAME
from countries c
NATURAL JOIN REGIONS ;

SELECT COUNTRIES.COUNTRY_NAME, REGIONS.REGION_NAME 
FROM COUNTRIES
INNER JOIN REGIONS 
ON REGIONS.REGION_ID = COUNTRIES.REGION_ID ;

-- LEFT JOIN

SELECT * FROM INVENTORIES;
SELECT * FROM WAREHOUSES ;
SELECT * FROM PRODUCTS ;

SELECT INV.QUANTITY,PRO.PRODUCT_NAME, WAR.WAREHOUSE_NAME
FROM INVENTORIES INV
LEFT JOIN PRODUCTS PRO ON PRO.PRODUCT_ID = INV.PRODUCT_ID 
LEFT JOIN WAREHOUSES WAR ON WAR.WAREHOUSE_ID = INV.WAREHOUSE_ID ;

-- Full Outer Join

SELECT INV.QUANTITY,PRO.PRODUCT_NAME, WAR.WAREHOUSE_NAME
FROM INVENTORIES INV
Full OUTER JOIN PRODUCTS PRO ON PRO.PRODUCT_ID = INV.PRODUCT_ID 
Full OUTER JOIN WAREHOUSES WAR ON WAR.WAREHOUSE_ID = INV.WAREHOUSE_ID ;
